In [1]:
import pandas as pd

## Target website: https://www.football-data.co.uk/data.php

In [2]:
#Reading the  csv file from the site 
dataF = pd.read_csv(r"https://www.football-data.co.uk/mmz4281/2526/E0.csv")

# Read a .csv file from a URL with Pandas

In [3]:
dataF.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [9]:
#renaming the columns
dataF.rename(columns={ 'FTHG' :'home_goals',
               'FTAG': 'away_goals' }, inplace = True)

In [10]:
dataF

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

# Read .csv from Multiple Urls with pandas

### Link:root + season + league

In [14]:
#link structure/ every link has a smilar part instead of parts
"https://www.football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

'https://www.football-data.co.uk/mmz4281/2526/E0.csv'

In [9]:
#root variable link/ the part of the link i.e same for every other links
root = "https://www.football-data.co.uk/mmz4281/"

## Multiple leagues
### 1.https://www.football-data.co.uk/mmz4281/2122/E0.csv
### 2.https://www.football-data.co.uk/mmz4281/2122/E1.csv
### 3.https://www.football-data.co.uk/mmz4281/2122/E2.csv
### 4.https://www.football-data.co.uk/mmz4281/2122/E3.csv
### 5.https://www.football-data.co.uk/mmz4281/2122/EC.csv

In [10]:
#creating list of leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames = []           #a list

#looping through leagues, read multiple csv and append in into a list
for league in leagues:
    df = pd.read_csv( root + '2122' + '/' + league + '.csv', encoding ='unicode_escape')
    frames.append(df)    #to store each df when a new iteration begins as the old df will be lost (to protect them use append)

In [11]:
# length of frames (total intems in a element)
len(frames)

5

In [12]:
#checking index of frames and seeing the DFs enterned
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,EC,21/08/2021,15:00,Aldershot,Chesterfield,0,2,A,0,0,...,1.93,0.50,1.98,1.83,2.03,1.83,2.05,1.90,1.97,1.80
1,EC,21/08/2021,15:00,Barnet,Notts County,0,5,A,0,0,...,2.06,0.75,1.88,1.93,1.90,1.95,2.00,1.95,1.90,1.88
2,EC,21/08/2021,15:00,Halifax,Maidenhead,1,2,A,1,0,...,1.94,-0.50,1.93,1.88,1.99,1.87,2.03,1.93,1.94,1.84
3,EC,21/08/2021,15:00,Kings Lynn,Southend,0,1,A,0,1,...,1.91,0.25,1.75,2.05,1.81,2.06,1.90,2.11,1.76,2.02
4,EC,21/08/2021,15:00,Solihull,Wrexham,2,2,D,1,2,...,1.85,0.00,2.05,1.75,1.93,1.92,2.05,1.98,1.92,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,EC,15/05/2022,15:00,Dover Athletic,Weymouth,1,2,A,0,1,...,2.50,0.25,1.88,1.93,1.87,1.98,1.90,1.98,1.85,1.93
502,EC,15/05/2022,15:00,Eastleigh,Grimsby,4,4,D,0,2,...,2.30,0.50,1.88,1.93,1.88,1.98,1.95,1.98,1.87,1.90
503,EC,15/05/2022,15:00,Maidenhead,Notts County,0,1,A,0,0,...,2.42,0.50,1.95,1.85,2.03,1.83,2.03,1.96,1.92,1.87
504,EC,15/05/2022,15:00,Southend,Torquay,1,1,D,0,1,...,2.01,-0.25,2.02,1.77,2.03,1.83,2.07,1.85,2.00,1.80
505,EC,15/05/2022,15:00,Stockport,Halifax,2,0,H,1,0,...,1.97,-0.75,1.80,2.00,1.79,2.08,1.93,2.08,1.84,1.95

## 2.2 Multiple Seasons (now extracting data for multiple seasons)

In [13]:
for season in range(15, 21):
    print(str(season) + str(season+1))

1516
1617
1718
1819
1920
2021

In [14]:
#creating list of leagues
leagues = ['E0', 'E1', 'E2']
frames = []           #a list

#looping through leagues, read multiple csv and append in into a list
for league in leagues:
    for season in range(15, 21):
        df = pd.read_csv( root + str(season) + str(season+1) + '/' + league + '.csv',)
        df.insert(1,'season',season)
        frames.append(df)

In [15]:
#total frames (6 seasons x 3 leagues)
len(frames)

18

In [16]:
frames[0]

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,1.79,26,-0.50,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,1.99,27,-1.50,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,1.96,26,-1.00,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,1.67,26,-0.50,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,2.01,26,-1.00,2.20,2.09,1.82,1.78,1.64,4.07,6.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,15,15/05/2016,Stoke,West Ham,2,1,H,0,1,...,2.27,30,0.25,2.11,2.03,1.87,1.83,3.05,4.00,2.26
376,E0,15,15/05/2016,Swansea,Man City,1,1,D,1,1,...,2.45,31,1.00,2.14,2.05,1.85,1.81,7.05,5.00,1.47
377,E0,15,15/05/2016,Watford,Sunderland,2,2,D,0,1,...,2.10,29,-0.50,2.06,2.01,1.91,1.85,1.64,4.52,5.27
378,E0,15,15/05/2016,West Brom,Liverpool,1,1,D,1,1,...,2.09,30,-0.25,2.10,2.05,1.86,1.81,2.61,3.75,2.70
379,E0,15,17/05/2016,Man United,Bournemouth,3,1,H,1,0,...,2.20,29,-0.75,1.88,1.84,2.08,2.02,1.50,4.60,7.03

In [17]:
frames[5]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,20,12/09/2020,12:30,Fulham,Arsenal,0,3,A,0,...,1.84,0.75,2.01,1.89,2.02,1.91,2.13,1.92,2.02,1.87
1,E0,20,12/09/2020,15:00,Crystal Palace,Southampton,1,0,H,1,...,1.70,0.25,1.78,2.13,1.79,2.17,1.85,2.18,1.79,2.12
2,E0,20,12/09/2020,17:30,Liverpool,Leeds,4,3,H,3,...,2.62,-1.50,1.85,2.05,1.85,2.08,1.90,2.16,1.84,2.04
3,E0,20,12/09/2020,20:00,West Ham,Newcastle,0,2,A,0,...,1.92,-0.50,2.03,1.87,2.04,1.88,2.09,1.91,2.02,1.86
4,E0,20,13/09/2020,14:00,West Brom,Leicester,0,3,A,0,...,1.73,0.25,1.92,1.98,1.93,1.99,1.95,2.01,1.91,1.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,16:00,Liverpool,Crystal Palace,2,0,H,1,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,20,23/05/2021,16:00,Man City,Everton,5,0,H,2,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,20,23/05/2021,16:00,Sheffield United,Burnley,1,0,H,1,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,20,23/05/2021,16:00,West Ham,Southampton,3,0,H,2,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,20,23/05/2021,16:00,Wolves,Man United,1,2,A,1,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88

# 3.Organize all the data in a dictionary

In [18]:
import pandas as pd

In [19]:
# creat a dictionary with original name of the league as key 
dict_countries={ 'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
                  'Gernman Bundesliga':'D1', 'English Premier League':'E0',
                  'English League 1': 'E2'
}

In [20]:
#get a dict element
dict_countries['Spanish La Liga']

'SP1'

In [23]:
#loop through key elements
dict_historical_data = {}

In [5]:
for league in dict_countries:
    print(dict_countries[league])

SP1
SP2
D1
E0
E2

In [24]:
#creating list of leagues
#leagues = ['E0', 'E1', 'E2']
frames = []          

#looping through leagues, read multiple csv and append in into a list
for league in dict_countries:
    for season in range(15, 21):
        df = pd.read_csv( root + str(season) + str(season+1) + '/' + dict_countries[league] + '.csv',)
        df.insert(1,'season',season)
        frames.append(df) 
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [27]:
#show keys of the df
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Segunda Division', 'Gernman Bundesliga', 'English Premier League', 'English League 1'])

In [30]:
#show dataframe inside dict_historical_data
dict_historical_data['Gernman Bundesliga']   #better than keeping the index in mind and remembering the code

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,SP1,15,21/08/15,Malaga,Sevilla,0,0,D,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,15,22/08/15,Ath Madrid,Las Palmas,1,0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,15,22/08/15,Espanol,Getafe,1,0,H,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,15,22/08/15,La Coruna,Sociedad,0,0,D,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,15,22/08/15,Vallecano,Valencia,0,0,D,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,D1,20,22/05/2021,Hoffenheim,Hertha,2,1,H,0.0,1.0,...,2.96,-0.75,1.86,2.07,1.88,2.06,1.99,2.08,1.88,2.00
302,D1,20,22/05/2021,Stuttgart,Bielefeld,0,2,A,0.0,0.0,...,2.50,-0.25,2.03,1.90,2.02,1.90,2.06,1.91,2.01,1.87
303,D1,20,22/05/2021,Union Berlin,RB Leipzig,2,1,H,0.0,0.0,...,2.34,0.50,1.97,1.96,1.97,1.95,1.98,1.98,1.92,1.95
304,D1,20,22/05/2021,Werder Bremen,M'gladbach,2,4,A,0.0,1.0,...,2.52,0.25,2.04,1.89,2.03,1.90,2.07,1.91,2.00,1.87
305,D1,20,22/05/2021,Wolfsburg,Mainz,2,3,A,0.0,1.0,...,2.97,-0.75,2.05,1.75,2.09,1.83,2.13,1.89,2.04,1.83